# Generated by Django 4.2.4 on 2025-08-14 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneAd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marka', models.CharField(max_length=255)),
                ('holati', models.CharField(max_length=255)),
                ('batareka_holati', models.CharField(max_length=255)),
                ('rangi', models.CharField(max_length=50)),
                ('komplekt', models.CharField(max_length=255)),
                ('narx_usd', models.DecimalField(decimal_places=2, max_digits=10)),
                ('obmen', models.BooleanField(default=False)),
                ('manzil', models.CharField(max_length=255)),
                ('tel_raqam', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('sold', 'Sold'), ('inactive', 'Inactive')], default='active', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ads', to='bot.tguser')),
            ],
        ),
        migrations.CreateModel(
            name='PhoneAdImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_id', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='bot.phonead')),
            ],
        ),
    ]
