# Generated by Django 5.2.1 on 2025-08-17 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_phonead_phoneadimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phonead',
            name='narx_usd',
        ),
        migrations.AddField(
            model_name='phonead',
            name='narx_usd_sum',
            field=models.CharField(default='+998909096835', max_length=50),
            preserve_default=False,
        ),
    ]
