# Generated by Django 5.2.1 on 2025-08-18 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_remove_phonead_narx_usd_phonead_narx_usd_sum'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonead',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
    ]
