# Generated by Django 5.2.1 on 2025-08-23 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_phonead_is_published'),
    ]

    operations = [
        migrations.CreateModel(
            name='BroadcastTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_chat_id', models.BigIntegerField()),
                ('message_id', models.BigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed', models.BooleanField(default=False)),
                ('last_user_id', models.BigIntegerField(default=0)),
            ],
        ),
    ]
