# Generated by Django 5.2.1 on 2025-08-23 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0005_broadcasttask'),
    ]

    operations = [
        migrations.RenameField(
            model_name='broadcasttask',
            old_name='completed',
            new_name='finished',
        ),
        migrations.RemoveField(
            model_name='broadcasttask',
            name='last_user_id',
        ),
        migrations.AddField(
            model_name='broadcasttask',
            name='failed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='broadcasttask',
            name='sent',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='broadcasttask',
            name='total',
            field=models.IntegerField(default=0),
        ),
    ]
