# Generated by Django 5.2.1 on 2025-08-23 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0006_rename_completed_broadcasttask_finished_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='broadcasttask',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
