# Generated by Django 5.2.1 on 2025-08-25 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0007_broadcasttask_finished_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonead',
            name='xotira',
            field=models.CharField(default=' ', max_length=255),
            preserve_default=False,
        ),
    ]
