# Generated by Django 5.2.1 on 2025-08-28 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0008_phonead_xotira'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonead',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='phonead',
            name='payment_image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
