# Generated by Django 6.0.3 on 2026-04-04 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0009_phonead_is_paid_phonead_payment_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('model', 'Model'), ('question', 'Question'), ('answer', 'Answer')], max_length=10)),
                ('text', models.CharField(max_length=255)),
                ('price_change', models.IntegerField(default=0)),
                ('order', models.IntegerField(default=0)),
                ('allow_skip', models.BooleanField(default=False)),
                ('final_text', models.TextField(blank=True)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='bot.pricingnode')),
                ('show_if_answer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bot.pricingnode')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PricingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.IntegerField(default=0)),
                ('price_preview', models.IntegerField(default=0)),
                ('answers', models.ManyToManyField(blank=True, related_name='answer_sessions', to='bot.pricingnode')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='model_sessions', to='bot.pricingnode')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.tguser')),
            ],
        ),
    ]
