# Generated by Django 6.0.3 on 2026-04-04 18:46

import django.db.models.deletion
import mptt.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0010_pricingnode_pricingsession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricingnode',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='bot.pricingnode'),
        ),
        migrations.AlterField(
            model_name='pricingnode',
            name='show_if_answer',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conditional_children', to='bot.pricingnode'),
        ),
    ]
