# Generated by Django 6.0.3 on 2026-04-05 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0011_alter_pricingnode_parent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricingnode',
            name='icon',
            field=models.CharField(blank=True, help_text='Emoji icon (💾 🎨 🔋 etc)', max_length=10),
        ),
        migrations.AddField(
            model_name='pricingnode',
            name='label',
            field=models.CharField(blank=True, help_text='Label shown in result (example: Storage, Color)', max_length=100),
        ),
    ]
