# Generated by Django 6.0.3 on 2026-04-05 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0012_pricingnode_icon_pricingnode_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricingsession',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
