# Generated by Django 6.0.3 on 2026-04-05 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0013_pricingsession_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricingnode',
            name='final_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
