# Generated by Django 6.0.3 on 2026-04-05 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0014_alter_pricingnode_final_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='tguser',
            name='pricing_expire',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tguser',
            name='pricing_limit',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tguser',
            name='pricing_used',
            field=models.IntegerField(default=0),
        ),
    ]
