# Generated by Django 6.0.3 on 2026-04-06 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0015_tguser_pricing_expire_tguser_pricing_limit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tguser',
            name='step_package',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
