# Generated by Django 6.0.3 on 2026-04-06 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0016_tguser_step_package'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricingsession',
            name='final_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pricingsession',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pricingsession',
            name='is_posted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pricingsession',
            name='manzil',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='pricingsession',
            name='obmen',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pricingsession',
            name='payment_image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pricingsession',
            name='tel_raqam',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.CreateModel(
            name='PricingSessionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_id', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='bot.pricingsession')),
            ],
        ),
    ]
